data_parameters:
  batch_size: 64
  cat_encoding: int
  scaling_type: minmax
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo
model_parameters:
  algorithm: auto
  contamination: 0.01
  leaf_size: 30
  method: largest
  metric: manhattan
  n_neighbors: 50
  p: 2
