data_parameters:
  batch_size: 1000
  cat_encoding: onehot
  scaling_type: minmax
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo
model_parameters:
  act: Tanh
  bias: false
  hidden_dims: 512,256
  lr: 0.001
  max_samples: 128
  n_ensemble: 20
  n_estimators: 3
  rep_dim: 256
