data_parameters:
  batch_size: 512
  cat_encoding: int
  scaling_type: standard
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo
model_parameters:
  basis_vector_num: 5
  cl: true
  cl_ratio: 0.09
  de_nlayers: 3
  diversity: true
  en_nlayers: 3
  epochs: 200
  hidden_dim: 128
  input_info: true
  input_info_ratio: 0.15
  learning_rate: 0.005
  plearn: false
  sche_gamma: 0.98
