data_parameters:
  batch_size: 64
  cat_encoding: onehot
  scaling_type: standard
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo
model_parameters:
  algorithm: auto
  contamination: 0.1
  leaf_size: 30
  method: median
  metric: euclidean
  n_neighbors: 10
  p: 2
