data_parameters:
  batch_size: 64
  cat_encoding: onehot
  scaling_type: minmax
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo
model_parameters:
  algorithm: auto
  contamination: 0.1
  leaf_size: 50
  metric: cosine
  n_neighbors: 10
  novelty: true
  p: 2
