data_parameters:
  batch_size: 64
  cat_encoding: onehot
  scaling_type: standard
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo
model_parameters:
  bootstrap: false
  contamination: 0.15
  max_features: 1.0
  max_samples: 0.7
  n_estimators: 200
  random_state: 42
